### ISSUE TITLE
HexBug not running after deletion of Hexbound

### ISSUE THREAD

**Issue by JohnDog3112** [object-Object/HexBug#30]
I tried running the generate_pattern_info.py script the other day but the program failed to compile because it could find [https://hexbound.cypher.coffee/0.1.3+1.19.2/docs.json](https://hexbound.cypher.coffee/0.1.3+1.19.2/docs.json )

logs: [log.txt](https://github.com/user-attachments/files/15746314/log.txt)

It seems the call comes from [here](https://github.com/object-Object/HexBug/blob/d5a37eba6d5e4f41726150164dd335ea46e6f880/src/HexBug/utils/mods.py#L463), but I'm not sure.

**Comment by object-Object** [comment]
Temporarily fixed in 9214008d5384ec7b5b191b12754ba94940f03ca0 by removing Hexbound; I'll re-add it if/when I get around to setting it up with a hexdoc plugin.
